dj6pmApril/registerEmail/registerEmail/urls.py
from django.conf.urls import url
from django.contrib import admin
from myapp import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.regView,name='index'),
    url(r'^otp',views.genOTP,name='genOTP')
]

dj6pmApril/registerEmail/myapp/models.py
from django.db import models
from django.contrib.auth.models import User

class registration(models.Model):
    user = models.OneToOneField(User,on_delete = models.CASCADE)

    def __str__(self):
        return self.user.username

dj6pmApril/registerEmail/myapp/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import registration

class regForm(forms.ModelForm):
    confirm_password = forms.CharField(widget= forms.PasswordInput())
    enter_OTP = forms.IntegerField()
    class Meta:
        model = User
        fields = ('first_name','last_name','username','email','password')
        widgets = {
        'password':forms.PasswordInput(attrs={'type':'password'})
        }

dj6pmApril/registerEmail/myapp/views.py
from django.shortcuts import render
from .forms import regForm
import random
from django.http import HttpResponse
from .models import registration
from django.contrib.auth.models import User
from django.core.mail import EmailMessage

def regView(request):
    form = regForm()
    if request.method == 'POST':
        form = regForm(data=request.POST)

        if form.is_valid():
            user = form.save()
            user.set_password(user.password)
            user.save()
            return render(request,'index.html',{'form':form,'m':'Register Successfully'})

    return render(request,'index.html',{'form':form})

def genOTP(request):
    try:
        name= 'Customer'
        otp = random.randint(100000,999999)
        print(otp)
        subject = 'Account Activation'
        if 'name' in request.GET:
            name = request.GET['name']
        message = 'Dear {} \n {} is your One Time Password for registration \n Thanks for being a part of our organization\n Do not share it with anyone'.format(name,otp)
        receiver = str(request.GET['email'])
        email = EmailMessage(subject,message,to=[receiver,])
        email.send()
        response = ['An OTP Sent to your Email Address @',otp]
        return HttpResponse(response)
    except:
        response = ['OOPs!! Error Occured @',otp]
        return HttpResponse(response)

dj6pmApril/registerEmail/templates/index.html
<!DOCTYPE html>
{% load bootstrap4 %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>REGISTER FORM</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <style media="screen">
      #id_first_name, #id_last_name{
        width:48.1%;
        float:left;
      }label{
        display:none;
      }
      #id_first_name, #id_last_name,#id_email, #id_username, #id_password, #id_confirm_password{
        margin: 10px 4px 10px 4px;
      }
      #id_last_name0{
        margin-left:10px;
      }
      .form-group > small{
        color:red !important;
      }
      #id_enter_OTP{
        display:none;
      }
    </style>
    <script>
      $(function(){
        var arr = [];
        $('#id_email').change(function(){
          var name = $('#id_first_name').val();
          var email = $('#id_email').val();
          $.ajax({
            url:'{% url "genOTP"%}',
            data:{name:name,email:email},
            success:function(data){
              arr = data.split('@');
              $('#res').html(arr[0]).addClass('alert alert-success');
              $('#id_enter_OTP').show(1000);
            }
          });
        });
        $('#verify').click(function(e){
          e.preventDefault();
          var uotp = $('#id_enter_OTP').val();
          if(uotp == arr[1]){
            $('#sb').removeAttr('disabled');
            $('#res').html('Verification Completed').addClass('alert alert-success');
          }
          else{
            $('#res').html('Verification Pending').addClass('alert alert-success');
          }
        });
        $('#id_confirm_password').keyup(function(){
          var pass = $('#id_password').val();
          var cpass = $('#id_confirm_password').val();
          if(pass!=cpass){
            $('#res').html('Password Does Not Match').addClass('alert alert-danger');
            $('#id_password').css({'border':'1px solid red'});
            $('#id_confirm_password').css({'border':'1px solid red'});
          }
          else{
            $('#res').html('').removeClass('alert alert-danger');
            $('#id_password').css({'border':'1px solid green'});
            $('#id_confirm_password').css({'border':'1px solid green'});
          }
        });
      });
    </script>
  </head>
  <body>
    {% if m %}
      <script>
        alert("Register Successfully!!!");
      </script>
    {% endif %}
    <div class="container-fluid bg-danger">
      <div class="row py-5">
        <div class="col-md-6 p-5 mx-auto bg-light text-white">
          <h2 class='text-danger'>Not have an Account? Register here</h2>
          <form class="" method="post">
            <p id='res'></p>
            {% csrf_token %}
            {% bootstrap_form form %}
            <a href="#" id='verify'>Verify OTP?</a>
            <input type="submit" id='sb' name="register" class='btn btn-primary btn-block' value="Register" style='' disabled>
          </form>
        </div>
      </div>
    </div>
  </body>
</html>